"useclient";
import { Inter } from "next/font/google";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import NavbarComponent from "./components/navbar/index.js";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AppRouterCacheProvider>
        <body className={inter.className}>
          <div className="nav-bar">
            <NavbarComponent />
          </div>
          <div id="root">
            {children}
          </div>
        </body>
      </AppRouterCacheProvider>
    </html>
  );
}
